use crate::ast::*;
use crate::compile_error::*;
use crate::error_context::*;
use crate::program::*;
use crate::val::*;
use num_bigint::BigInt;
use num_traits::Num;
use std::collections::HashMap;
use std::mem;
use std::str::FromStr;

// Branches can go forward as well as back
// so can only be resolved at the end, when all labels have been seen
// so need to keep track until then
struct Branch {
    // A branch might find no corresponding label
    // and need to report error
    ec: ErrorContext,

    // Index in the code vector
    i: usize,

    // Label referred to
    // This may be a label explicitly written by the programmer
    // or automatically generated by the compiler
    label: String,
}

struct Compiler<'a> {
    ast: &'a AST,

    // Counter for generating temporary names
    tmp_count: usize,

    branches: Vec<Branch>,
    labels: HashMap<String, usize>,

    code: Vec<Inst>,
}

fn parse_bigint(input: &str) -> Result<BigInt, String> {
    // Convert to bytes for easier prefix checking
    let bytes = input.as_bytes();

    // Check for prefixes and determine base
    if bytes.len() >= 2 && bytes[0] == b'0' {
        match bytes[1] {
            b'x' | b'X' => {
                // Hexadecimal (0x)
                let hex_str = &input[2..]; // Skip the '0x' prefix
                return BigInt::from_str_radix(hex_str, 16)
                    .map_err(|e| format!("Invalid hexadecimal: {}", e));
            }
            b'b' | b'B' => {
                // Binary (0b)
                let bin_str = &input[2..]; // Skip the '0b' prefix
                return BigInt::from_str_radix(bin_str, 2)
                    .map_err(|e| format!("Invalid binary: {}", e));
            }
            b'o' | b'O' => {
                // Octal (0o)
                let oct_str = &input[2..]; // Skip the '0o' prefix
                return BigInt::from_str_radix(oct_str, 8)
                    .map_err(|e| format!("Invalid octal: {}", e));
            }
            _ => {}
        }
    }

    // Default to decimal
    BigInt::from_str(input).map_err(|e| format!("Invalid decimal: {}", e))
}

impl<'a> Compiler<'a> {
    fn new(ast: &'a AST) -> Self {
        Compiler {
            ast,
            tmp_count: 0,
            labels: HashMap::<String, usize>::new(),
            branches: Vec::<Branch>::new(),
            code: Vec::<Inst>::new(),
        }
    }

    fn tmp(&mut self) -> String {
        self.tmp_count += 1;

        // Temporary names cannot clash with any valid identifier
        format!(" {}", self.tmp_count)
    }

    fn branch(&mut self, ec: &ErrorContext, br: Inst, label: &str) {
        self.branches.push(Branch {
            ec: ec.clone(),
            i: self.code.len(),
            label: label.to_string(),
        });
        self.code.push(br);
    }

    fn expr(&mut self, a: &Expr) -> Result<(), CompileError> {
        match a {
            Expr::True => {
                self.code.push(Inst::Const(Val::True));
            }
            Expr::False => {
                self.code.push(Inst::Const(Val::False));
            }
            Expr::Null => {
                self.code.push(Inst::Const(Val::Null));
            }
            Expr::Str(s) => {
                self.code.push(Inst::Const(Val::Str(s.clone().into())));
            }
            Expr::Float(ec, s) => {
                let s = s.replace('_', "");
                let a = match s.parse::<f64>() {
                    Ok(a) => a,
                    Err(e) => return Err(CompileError::new(ec.clone(), e.to_string())),
                };
                self.code.push(Inst::Const(Val::Float(a)));
            }
            Expr::Int(ec, s) => {
                let a = match parse_bigint(s) {
                    Ok(a) => a,
                    Err(e) => return Err(CompileError::new(ec.clone(), e.to_string())),
                };
                self.code.push(Inst::Const(Val::Int(a)));
            }
            Expr::Call(ec, f, args) => {
                if let Expr::Id(_, name) = &**f {
                    for a in args {
                        self.expr(a)?;
                    }
                    self.code
                        .push(Inst::Call(ec.clone(), name.to_string(), args.len()));
                    return Ok(());
                }
                self.expr(f)?;
                for a in args {
                    self.expr(a)?;
                }
                self.code.push(Inst::CallIndirect(ec.clone(), args.len()));
            }
            Expr::Id(ec, name) => {
                self.code.push(Inst::Load(ec.clone(), name.to_string()));
            }
            Expr::Add(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Add);
            }
            Expr::Sub(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Sub(ec.clone()));
            }
            Expr::Mul(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Mul(ec.clone()));
            }
            Expr::IDiv(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::IDiv(ec.clone()));
            }
            Expr::FDiv(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::FDiv(ec.clone()));
            }
            Expr::Mod(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Mod(ec.clone()));
            }
            Expr::Eq(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Eq);
            }
            Expr::Ne(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Ne);
            }
            Expr::Lt(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Lt);
            }
            Expr::Gt(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Gt);
            }
            Expr::Le(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Le);
            }
            Expr::Ge(a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Ge);
            }
            Expr::Shl(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Shl(ec.clone()));
            }
            Expr::Shr(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Shr(ec.clone()));
            }
            Expr::BitAnd(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::BitAnd(ec.clone()));
            }
            Expr::BitOr(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::BitOr(ec.clone()));
            }
            Expr::BitXor(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::BitXor(ec.clone()));
            }
            Expr::Pow(ec, a, b) => {
                self.expr(a)?;
                self.expr(b)?;
                self.code.push(Inst::Pow(ec.clone()));
            }
            Expr::Neg(ec, a) => {
                self.expr(a)?;
                self.code.push(Inst::Neg(ec.clone()));
            }
            Expr::Not(a) => {
                self.expr(a)?;
                self.code.push(Inst::Not);
            }
            Expr::BitNot(ec, a) => {
                self.expr(a)?;
                self.code.push(Inst::BitNot(ec.clone()));
            }
            Expr::Assign(_ec, a, b) => match &**a {
                Expr::Id(_, name) => {
                    self.expr(b)?;
                    self.code.push(Inst::Store(name.to_string()));
                }
                Expr::Call(ec, a, indexes) => {
                    if indexes.len() != 1 {
                        return Err(CompileError::new(
                            ec.clone(),
                            "Expected one index".to_string(),
                        ));
                    }
                    self.expr(a)?;
                    self.expr(&indexes[0])?;
                    self.expr(b)?;
                    self.code.push(Inst::StoreAt(ec.clone()));
                }
                _ => {
                    eprintln!("{:?}", a);
                    eprintln!("{:?}", b);
                    todo!();
                }
            },
            _ => {
                eprintln!("{:?}", a);
                todo!();
            }
        }
        Ok(())
    }

    fn stmt(&mut self, a: &Stmt) -> Result<(), CompileError> {
        match a {
            Stmt::Assert(ec, cond, msg) => {
                self.expr(cond)?;
                self.code.push(Inst::Assert(ec.clone(), msg.to_string()));
            }
            Stmt::Print(ec, v) => {
                for a in v {
                    self.expr(a)?;
                    self.code
                        .push(Inst::Call(ec.clone(), "_print".to_string(), 1));
                }
            }
            Stmt::Label(ec, s) => match self.labels.insert(s.to_string(), self.code.len()) {
                Some(_) => {
                    return Err(CompileError::new(
                        ec.clone(),
                        format!("'{}' was already defined", s),
                    ));
                }
                _ => {}
            },
            Stmt::Goto(ec, label) => self.branch(ec, Inst::Br(0), label),
            Stmt::DoWhile(cond, body) => {
                // Body
                let loop_label = self.tmp();
                self.labels.insert(loop_label.clone(), self.code.len());
                self.block(body)?;

                // Condition
                self.expr(cond)?;
                self.branch(&ErrorContext::blank(), Inst::BrTrue(0), &loop_label);
            }
            Stmt::While(cond, body) => {
                // Bypass
                let cond_label = self.tmp();
                self.branch(&ErrorContext::blank(), Inst::Br(0), &cond_label);

                // Body
                let loop_label = self.tmp();
                self.labels.insert(loop_label.clone(), self.code.len());
                self.block(body)?;

                // Condition
                self.labels.insert(cond_label, self.code.len());
                self.expr(cond)?;
                self.branch(&ErrorContext::blank(), Inst::BrTrue(0), &loop_label);
            }
            Stmt::If(cond, yes, no) => {
                // Condition
                self.expr(cond)?;
                let else_label = self.tmp();
                self.branch(&ErrorContext::blank(), Inst::BrFalse(0), &else_label);

                // Then
                self.block(yes)?;
                let after_label = self.tmp();
                self.branch(&ErrorContext::blank(), Inst::Br(0), &after_label);

                // Else
                self.labels.insert(else_label, self.code.len());
                self.block(no)?;

                // After
                self.labels.insert(after_label, self.code.len());
            }
            Stmt::Expr(a) => {
                self.expr(a)?;
                self.code.push(Inst::Pop);
            }
            _ => {
                eprintln!("{:?}", a);
                todo!();
            }
        }
        Ok(())
    }

    fn block(&mut self, v: &Vec<Stmt>) -> Result<(), CompileError> {
        for a in v {
            self.stmt(&a)?;
        }
        Ok(())
    }

    fn compile(&mut self) -> Result<Program, CompileError> {
        // Generate code
        self.block(&self.ast.code)?;

        // Resolve branches
        for branch in &self.branches {
            let target = match self.labels.get(&branch.label) {
                Some(i) => *i,
                None => {
                    return Err(CompileError::new(
                        branch.ec.clone(),
                        format!("'{}' not found", branch.label),
                    ));
                }
            };
            let br = &self.code[branch.i];
            self.code[branch.i] = match br {
                Inst::Br(_) => Inst::Br(target),
                Inst::BrFalse(_) => Inst::BrFalse(target),
                Inst::BrTrue(_) => Inst::BrTrue(target),
                _ => {
                    eprintln!("{:?}", br);
                    todo!();
                }
            };
        }

        Ok(Program {
            code: mem::take(&mut self.code),
        })
    }
}

pub fn compile(ast: &AST) -> Result<Program, CompileError> {
    let mut compiler = Compiler::new(ast);
    compiler.compile()
}
