\set ON_ERROR_STOP true
\c verbena
BEGIN;
INSERT INTO country(Name,Code) VALUES ('Afghanistan','AF');
INSERT INTO country(Name,Code) VALUES ('Åland Islands','AX');
INSERT INTO country(Name,Code) VALUES ('Albania','AL');
INSERT INTO country(Name,Code) VALUES ('Algeria','DZ');
INSERT INTO country(Name,Code) VALUES ('American Samoa','AS');
INSERT INTO country(Name,Code) VALUES ('Andorra','AD');
INSERT INTO country(Name,Code) VALUES ('Angola','AO');
INSERT INTO country(Name,Code) VALUES ('Anguilla','AI');
INSERT INTO country(Name,Code) VALUES ('Antarctica','AQ');
INSERT INTO country(Name,Code) VALUES ('Antigua and Barbuda','AG');
INSERT INTO country(Name,Code) VALUES ('Argentina','AR');
INSERT INTO country(Name,Code) VALUES ('Armenia','AM');
INSERT INTO country(Name,Code) VALUES ('Aruba','AW');
INSERT INTO country(Name,Code) VALUES ('Australia','AU');
INSERT INTO country(Name,Code) VALUES ('Austria','AT');
INSERT INTO country(Name,Code) VALUES ('Azerbaijan','AZ');
INSERT INTO country(Name,Code) VALUES ('Bahamas','BS');
INSERT INTO country(Name,Code) VALUES ('Bahrain','BH');
INSERT INTO country(Name,Code) VALUES ('Bangladesh','BD');
INSERT INTO country(Name,Code) VALUES ('Barbados','BB');
INSERT INTO country(Name,Code) VALUES ('Belarus','BY');
INSERT INTO country(Name,Code) VALUES ('Belgium','BE');
INSERT INTO country(Name,Code) VALUES ('Belize','BZ');
INSERT INTO country(Name,Code) VALUES ('Benin','BJ');
INSERT INTO country(Name,Code) VALUES ('Bermuda','BM');
INSERT INTO country(Name,Code) VALUES ('Bhutan','BT');
INSERT INTO country(Name,Code) VALUES ('Bolivia, Plurinational State of','BO');
INSERT INTO country(Name,Code) VALUES ('Bonaire, Sint Eustatius and Saba','BQ');
INSERT INTO country(Name,Code) VALUES ('Bosnia and Herzegovina','BA');
INSERT INTO country(Name,Code) VALUES ('Botswana','BW');
INSERT INTO country(Name,Code) VALUES ('Bouvet Island','BV');
INSERT INTO country(Name,Code) VALUES ('Brazil','BR');
INSERT INTO country(Name,Code) VALUES ('British Indian Ocean Territory','IO');
INSERT INTO country(Name,Code) VALUES ('Brunei Darussalam','BN');
INSERT INTO country(Name,Code) VALUES ('Bulgaria','BG');
INSERT INTO country(Name,Code) VALUES ('Burkina Faso','BF');
INSERT INTO country(Name,Code) VALUES ('Burundi','BI');
INSERT INTO country(Name,Code) VALUES ('Cambodia','KH');
INSERT INTO country(Name,Code) VALUES ('Cameroon','CM');
INSERT INTO country(Name,Code) VALUES ('Canada','CA');
INSERT INTO country(Name,Code) VALUES ('Cape Verde','CV');
INSERT INTO country(Name,Code) VALUES ('Cayman Islands','KY');
INSERT INTO country(Name,Code) VALUES ('Central African Republic','CF');
INSERT INTO country(Name,Code) VALUES ('Chad','TD');
INSERT INTO country(Name,Code) VALUES ('Chile','CL');
INSERT INTO country(Name,Code) VALUES ('China','CN');
INSERT INTO country(Name,Code) VALUES ('Christmas Island','CX');
INSERT INTO country(Name,Code) VALUES ('Cocos (Keeling) Islands','CC');
INSERT INTO country(Name,Code) VALUES ('Colombia','CO');
INSERT INTO country(Name,Code) VALUES ('Comoros','KM');
INSERT INTO country(Name,Code) VALUES ('Congo','CG');
INSERT INTO country(Name,Code) VALUES ('Congo, the Democratic Republic of the','CD');
INSERT INTO country(Name,Code) VALUES ('Cook Islands','CK');
INSERT INTO country(Name,Code) VALUES ('Costa Rica','CR');
INSERT INTO country(Name,Code) VALUES ('Côte d''Ivoire','CI');
INSERT INTO country(Name,Code) VALUES ('Croatia','HR');
INSERT INTO country(Name,Code) VALUES ('Cuba','CU');
INSERT INTO country(Name,Code) VALUES ('Curaçao','CW');
INSERT INTO country(Name,Code) VALUES ('Cyprus','CY');
INSERT INTO country(Name,Code) VALUES ('Czech Republic','CZ');
INSERT INTO country(Name,Code) VALUES ('Denmark','DK');
INSERT INTO country(Name,Code) VALUES ('Djibouti','DJ');
INSERT INTO country(Name,Code) VALUES ('Dominica','DM');
INSERT INTO country(Name,Code) VALUES ('Dominican Republic','DO');
INSERT INTO country(Name,Code) VALUES ('Ecuador','EC');
INSERT INTO country(Name,Code) VALUES ('Egypt','EG');
INSERT INTO country(Name,Code) VALUES ('El Salvador','SV');
INSERT INTO country(Name,Code) VALUES ('Equatorial Guinea','GQ');
INSERT INTO country(Name,Code) VALUES ('Eritrea','ER');
INSERT INTO country(Name,Code) VALUES ('Estonia','EE');
INSERT INTO country(Name,Code) VALUES ('Ethiopia','ET');
INSERT INTO country(Name,Code) VALUES ('Falkland Islands (Malvinas)','FK');
INSERT INTO country(Name,Code) VALUES ('Faroe Islands','FO');
INSERT INTO country(Name,Code) VALUES ('Fiji','FJ');
INSERT INTO country(Name,Code) VALUES ('Finland','FI');
INSERT INTO country(Name,Code) VALUES ('France','FR');
INSERT INTO country(Name,Code) VALUES ('French Guiana','GF');
INSERT INTO country(Name,Code) VALUES ('French Polynesia','PF');
INSERT INTO country(Name,Code) VALUES ('French Southern Territories','TF');
INSERT INTO country(Name,Code) VALUES ('Gabon','GA');
INSERT INTO country(Name,Code) VALUES ('Gambia','GM');
INSERT INTO country(Name,Code) VALUES ('Georgia','GE');
INSERT INTO country(Name,Code) VALUES ('Germany','DE');
INSERT INTO country(Name,Code) VALUES ('Ghana','GH');
INSERT INTO country(Name,Code) VALUES ('Gibraltar','GI');
INSERT INTO country(Name,Code) VALUES ('Greece','GR');
INSERT INTO country(Name,Code) VALUES ('Greenland','GL');
INSERT INTO country(Name,Code) VALUES ('Grenada','GD');
INSERT INTO country(Name,Code) VALUES ('Guadeloupe','GP');
INSERT INTO country(Name,Code) VALUES ('Guam','GU');
INSERT INTO country(Name,Code) VALUES ('Guatemala','GT');
INSERT INTO country(Name,Code) VALUES ('Guernsey','GG');
INSERT INTO country(Name,Code) VALUES ('Guinea','GN');
INSERT INTO country(Name,Code) VALUES ('Guinea-Bissau','GW');
INSERT INTO country(Name,Code) VALUES ('Guyana','GY');
INSERT INTO country(Name,Code) VALUES ('Haiti','HT');
INSERT INTO country(Name,Code) VALUES ('Heard Island and McDonald Islands','HM');
INSERT INTO country(Name,Code) VALUES ('Holy See (Vatican City State)','VA');
INSERT INTO country(Name,Code) VALUES ('Honduras','HN');
INSERT INTO country(Name,Code) VALUES ('Hong Kong','HK');
INSERT INTO country(Name,Code) VALUES ('Hungary','HU');
INSERT INTO country(Name,Code) VALUES ('Iceland','IS');
INSERT INTO country(Name,Code) VALUES ('India','IN');
INSERT INTO country(Name,Code) VALUES ('Indonesia','ID');
INSERT INTO country(Name,Code) VALUES ('Iran, Islamic Republic of','IR');
INSERT INTO country(Name,Code) VALUES ('Iraq','IQ');
INSERT INTO country(Name,Code) VALUES ('Ireland','IE');
INSERT INTO country(Name,Code) VALUES ('Isle of Man','IM');
INSERT INTO country(Name,Code) VALUES ('Israel','IL');
INSERT INTO country(Name,Code) VALUES ('Italy','IT');
INSERT INTO country(Name,Code) VALUES ('Jamaica','JM');
INSERT INTO country(Name,Code) VALUES ('Japan','JP');
INSERT INTO country(Name,Code) VALUES ('Jersey','JE');
INSERT INTO country(Name,Code) VALUES ('Jordan','JO');
INSERT INTO country(Name,Code) VALUES ('Kazakhstan','KZ');
INSERT INTO country(Name,Code) VALUES ('Kenya','KE');
INSERT INTO country(Name,Code) VALUES ('Kiribati','KI');
INSERT INTO country(Name,Code) VALUES ('Korea, Democratic People''s Republic of','KP');
INSERT INTO country(Name,Code) VALUES ('Korea, Republic of','KR');
INSERT INTO country(Name,Code) VALUES ('Kuwait','KW');
INSERT INTO country(Name,Code) VALUES ('Kyrgyzstan','KG');
INSERT INTO country(Name,Code) VALUES ('Lao People''s Democratic Republic','LA');
INSERT INTO country(Name,Code) VALUES ('Latvia','LV');
INSERT INTO country(Name,Code) VALUES ('Lebanon','LB');
INSERT INTO country(Name,Code) VALUES ('Lesotho','LS');
INSERT INTO country(Name,Code) VALUES ('Liberia','LR');
INSERT INTO country(Name,Code) VALUES ('Libya','LY');
INSERT INTO country(Name,Code) VALUES ('Liechtenstein','LI');
INSERT INTO country(Name,Code) VALUES ('Lithuania','LT');
INSERT INTO country(Name,Code) VALUES ('Luxembourg','LU');
INSERT INTO country(Name,Code) VALUES ('Macao','MO');
INSERT INTO country(Name,Code) VALUES ('Macedonia, the Former Yugoslav Republic of','MK');
INSERT INTO country(Name,Code) VALUES ('Madagascar','MG');
INSERT INTO country(Name,Code) VALUES ('Malawi','MW');
INSERT INTO country(Name,Code) VALUES ('Malaysia','MY');
INSERT INTO country(Name,Code) VALUES ('Maldives','MV');
INSERT INTO country(Name,Code) VALUES ('Mali','ML');
INSERT INTO country(Name,Code) VALUES ('Malta','MT');
INSERT INTO country(Name,Code) VALUES ('Marshall Islands','MH');
INSERT INTO country(Name,Code) VALUES ('Martinique','MQ');
INSERT INTO country(Name,Code) VALUES ('Mauritania','MR');
INSERT INTO country(Name,Code) VALUES ('Mauritius','MU');
INSERT INTO country(Name,Code) VALUES ('Mayotte','YT');
INSERT INTO country(Name,Code) VALUES ('Mexico','MX');
INSERT INTO country(Name,Code) VALUES ('Micronesia, Federated States of','FM');
INSERT INTO country(Name,Code) VALUES ('Moldova, Republic of','MD');
INSERT INTO country(Name,Code) VALUES ('Monaco','MC');
INSERT INTO country(Name,Code) VALUES ('Mongolia','MN');
INSERT INTO country(Name,Code) VALUES ('Montenegro','ME');
INSERT INTO country(Name,Code) VALUES ('Montserrat','MS');
INSERT INTO country(Name,Code) VALUES ('Morocco','MA');
INSERT INTO country(Name,Code) VALUES ('Mozambique','MZ');
INSERT INTO country(Name,Code) VALUES ('Myanmar','MM');
INSERT INTO country(Name,Code) VALUES ('Namibia','NA');
INSERT INTO country(Name,Code) VALUES ('Nauru','NR');
INSERT INTO country(Name,Code) VALUES ('Nepal','NP');
INSERT INTO country(Name,Code) VALUES ('Netherlands','NL');
INSERT INTO country(Name,Code) VALUES ('New Caledonia','NC');
INSERT INTO country(Name,Code) VALUES ('New Zealand','NZ');
INSERT INTO country(Name,Code) VALUES ('Nicaragua','NI');
INSERT INTO country(Name,Code) VALUES ('Niger','NE');
INSERT INTO country(Name,Code) VALUES ('Nigeria','NG');
INSERT INTO country(Name,Code) VALUES ('Niue','NU');
INSERT INTO country(Name,Code) VALUES ('Norfolk Island','NF');
INSERT INTO country(Name,Code) VALUES ('Northern Mariana Islands','MP');
INSERT INTO country(Name,Code) VALUES ('Norway','NO');
INSERT INTO country(Name,Code) VALUES ('Oman','OM');
INSERT INTO country(Name,Code) VALUES ('Pakistan','PK');
INSERT INTO country(Name,Code) VALUES ('Palau','PW');
INSERT INTO country(Name,Code) VALUES ('Palestine, State of','PS');
INSERT INTO country(Name,Code) VALUES ('Panama','PA');
INSERT INTO country(Name,Code) VALUES ('Papua New Guinea','PG');
INSERT INTO country(Name,Code) VALUES ('Paraguay','PY');
INSERT INTO country(Name,Code) VALUES ('Peru','PE');
INSERT INTO country(Name,Code) VALUES ('Philippines','PH');
INSERT INTO country(Name,Code) VALUES ('Pitcairn','PN');
INSERT INTO country(Name,Code) VALUES ('Poland','PL');
INSERT INTO country(Name,Code) VALUES ('Portugal','PT');
INSERT INTO country(Name,Code) VALUES ('Puerto Rico','PR');
INSERT INTO country(Name,Code) VALUES ('Qatar','QA');
INSERT INTO country(Name,Code) VALUES ('Réunion','RE');
INSERT INTO country(Name,Code) VALUES ('Romania','RO');
INSERT INTO country(Name,Code) VALUES ('Russian Federation','RU');
INSERT INTO country(Name,Code) VALUES ('Rwanda','RW');
INSERT INTO country(Name,Code) VALUES ('Saint Barthélemy','BL');
INSERT INTO country(Name,Code) VALUES ('Saint Helena, Ascension and Tristan da Cunha','SH');
INSERT INTO country(Name,Code) VALUES ('Saint Kitts and Nevis','KN');
INSERT INTO country(Name,Code) VALUES ('Saint Lucia','LC');
INSERT INTO country(Name,Code) VALUES ('Saint Martin (French part)','MF');
INSERT INTO country(Name,Code) VALUES ('Saint Pierre and Miquelon','PM');
INSERT INTO country(Name,Code) VALUES ('Saint Vincent and the Grenadines','VC');
INSERT INTO country(Name,Code) VALUES ('Samoa','WS');
INSERT INTO country(Name,Code) VALUES ('San Marino','SM');
INSERT INTO country(Name,Code) VALUES ('Sao Tome and Principe','ST');
INSERT INTO country(Name,Code) VALUES ('Saudi Arabia','SA');
INSERT INTO country(Name,Code) VALUES ('Senegal','SN');
INSERT INTO country(Name,Code) VALUES ('Serbia','RS');
INSERT INTO country(Name,Code) VALUES ('Seychelles','SC');
INSERT INTO country(Name,Code) VALUES ('Sierra Leone','SL');
INSERT INTO country(Name,Code) VALUES ('Singapore','SG');
INSERT INTO country(Name,Code) VALUES ('Sint Maarten (Dutch part)','SX');
INSERT INTO country(Name,Code) VALUES ('Slovakia','SK');
INSERT INTO country(Name,Code) VALUES ('Slovenia','SI');
INSERT INTO country(Name,Code) VALUES ('Solomon Islands','SB');
INSERT INTO country(Name,Code) VALUES ('Somalia','SO');
INSERT INTO country(Name,Code) VALUES ('South Africa','ZA');
INSERT INTO country(Name,Code) VALUES ('South Georgia and the South Sandwich Islands','GS');
INSERT INTO country(Name,Code) VALUES ('South Sudan','SS');
INSERT INTO country(Name,Code) VALUES ('Spain','ES');
INSERT INTO country(Name,Code) VALUES ('Sri Lanka','LK');
INSERT INTO country(Name,Code) VALUES ('Sudan','SD');
INSERT INTO country(Name,Code) VALUES ('Suriname','SR');
INSERT INTO country(Name,Code) VALUES ('Svalbard and Jan Mayen','SJ');
INSERT INTO country(Name,Code) VALUES ('Swaziland','SZ');
INSERT INTO country(Name,Code) VALUES ('Sweden','SE');
INSERT INTO country(Name,Code) VALUES ('Switzerland','CH');
INSERT INTO country(Name,Code) VALUES ('Syrian Arab Republic','SY');
INSERT INTO country(Name,Code) VALUES ('Taiwan, Province of China','TW');
INSERT INTO country(Name,Code) VALUES ('Tajikistan','TJ');
INSERT INTO country(Name,Code) VALUES ('Tanzania, United Republic of','TZ');
INSERT INTO country(Name,Code) VALUES ('Thailand','TH');
INSERT INTO country(Name,Code) VALUES ('Timor-Leste','TL');
INSERT INTO country(Name,Code) VALUES ('Togo','TG');
INSERT INTO country(Name,Code) VALUES ('Tokelau','TK');
INSERT INTO country(Name,Code) VALUES ('Tonga','TO');
INSERT INTO country(Name,Code) VALUES ('Trinidad and Tobago','TT');
INSERT INTO country(Name,Code) VALUES ('Tunisia','TN');
INSERT INTO country(Name,Code) VALUES ('Turkey','TR');
INSERT INTO country(Name,Code) VALUES ('Turkmenistan','TM');
INSERT INTO country(Name,Code) VALUES ('Turks and Caicos Islands','TC');
INSERT INTO country(Name,Code) VALUES ('Tuvalu','TV');
INSERT INTO country(Name,Code) VALUES ('Uganda','UG');
INSERT INTO country(Name,Code) VALUES ('Ukraine','UA');
INSERT INTO country(Name,Code) VALUES ('United Arab Emirates','AE');
INSERT INTO country(Name,Code) VALUES ('United Kingdom','GB');
INSERT INTO country(Name,Code) VALUES ('United States','US');
INSERT INTO country(Name,Code) VALUES ('United States Minor Outlying Islands','UM');
INSERT INTO country(Name,Code) VALUES ('Uruguay','UY');
INSERT INTO country(Name,Code) VALUES ('Uzbekistan','UZ');
INSERT INTO country(Name,Code) VALUES ('Vanuatu','VU');
INSERT INTO country(Name,Code) VALUES ('Venezuela, Bolivarian Republic of','VE');
INSERT INTO country(Name,Code) VALUES ('Viet Nam','VN');
INSERT INTO country(Name,Code) VALUES ('Virgin Islands, British','VG');
INSERT INTO country(Name,Code) VALUES ('Virgin Islands, U.S.','VI');
INSERT INTO country(Name,Code) VALUES ('Wallis and Futuna','WF');
INSERT INTO country(Name,Code) VALUES ('Western Sahara','EH');
INSERT INTO country(Name,Code) VALUES ('Yemen','YE');
INSERT INTO country(Name,Code) VALUES ('Zambia','ZM');
INSERT INTO country(Name,Code) VALUES ('Zimbabwe','ZW');
COMMIT;
