if 0 then print "false": print "false 2" else print "alt true": print "alt true 2"
if 1 then print "true": print "true 2" else print "alt false": print "alt false 2"

if 1 then
	print "a"
	print "a"
else
	print "b"
	print "b"
end

if 1 then
	print "a"
	print "a"
else
	print "b"
	print "b"
end if

if 1 then
	print "a"
	print "a"
else
	print "b"
	print "b"
endif

if 1
	print "a"
	print "a"
else
	print "b"
	print "b"
end

if 0
	print "a"
	print "a"
else
	print "b"
	print "b"
end
