print 1+2
print bitand(1, 3)
print -5
print bitand(-1, 1)
print 1/4
print 5-3
print 4*6
print 10 div 3
print 10 \ 3
print 10 mod 3
print 2^4

print
print 5>3
print 5<3
print 5>=5
print 5<=4
print 5=5
print 5==5
print 5!=5
print 5<>5

print
print bitand(5, 3)
print bitor(5, 3)
print bitxor(5, 3)
print 5 << 1
print 5 >> 1
print ~5

print
print sqr(4)
print sqr 4
print sqrt 4
print sqr 5

print
print int 1.1

assert 1+2=3
